
# ---- Stage 1: Build ----
    FROM maven:3.8.6-openjdk-17 AS build
    WORKDIR /app
    COPY . .
    RUN mvn clean package -DskipTests
    
    # ---- Stage 2: Run ----
    FROM maven:3.8.6-openjdk-17
    WORKDIR /app
    COPY --from=build /app/target/*.jar app.jar
    ENTRYPOINT ["java", "-jar", "app.jar"]
    